### ISSUE TITLE
Auction House function not working

### ISSUE THREAD

**Issue by SeanBradley67** [DelaneDiamon/Transmog-Checker#2]
Tried disabling all other addons - no checkbox appears once the AH is open. Unable to turn on that feature. 
![image](https://github.com/DelaneDiamon/Transmog-Checker/assets/75016450/220e0c2a-f514-4f50-94d3-2356d12ef4ed)

**Comment by DelaneDiamon** [comment]
Hey, should be resolved with 772336ce5907903f577b7321887da8d9b50eeaca
