### ISSUE TITLE
Grey and white items should be ignored

### ISSUE THREAD

**Issue by BreakBB** [DelaneDiamon/Transmog-Checker#3]
First of all: Thanks for this addon! ❤️ 

An improvement in my opinion would be to not see the tooltip lines on White and Grey items (or overall items which can not be collected as transmog at all).

**Comment by DelaneDiamon** [comment]
Hey, thanks a lot! 
I will look into that, I am not entirely sure why some items have additional sources (probably some greens that look like whites/greys), so I will filter that quality out.

Another improvement would be to exclude items which share models across different armor types - some mail items seem to have leather counterparts, so leather is showing as "not collected" for hunters while they cannot actually collect it.

**Comment by DelaneDiamon** [comment]
Hey, grey and white items should be now excluded with 2a6e682c9383d0079885229702d8e670457130d0
