### ISSUE TITLE
Display format is verbose - Suggesting a more elegant and user-friendly format

### ISSUE THREAD

**Issue by tamayopa** [DelaneDiamon/Transmog-Checker#8]
![image](https://github.com/user-attachments/assets/661d97e4-5167-40fd-a04e-078ae04cafb1)
![image](https://github.com/user-attachments/assets/4f180803-39fa-4ed5-8ea6-e41ccd3d261b)

Transmog Checker makes tooltips wider as you can see here.  With all due respect, it kinda feels like you're using back end wording for a front end display.  I'd like to suggest some different formats that would not only save a lot of space, but look much, much cleaner. So instead of this:
>${\color{red}{\textsf{Item Model: CLASS NOT ELIGIBLE TO COLLECT\}}}\$
${\color{YellowOrange}{\textsf{Exact Item Source: NOT COLLECTED \}}}\$

Try these:
## Suggestions
I'm including the class warning text on its own line as I suggested in issue DelaneDiamon/Transmog-Checker#7

**Lines vastly shortened**:
<sup>2 - 3 lines

>${\color{lime}{\textsf{Variant ✔\}}}\$
${\color{YellowOrange}{\textsf{Exact ✖ \}}}\$

>${\color{red}{\textsf{Class Invalid\}}}\$
${\color{lime}{\textsf{Variant: Yes\}}}\$
${\color{YellowOrange}{\textsf{Exact: No \}}}\$

---

**New line to maintain intuitive "The following is *addon text"* feel, regular conditions condensed to single line**:
<sup>2 - 3 lines
>${\{\textsf{Appearance:\}}}\$
${\color{lime}{\textsf{Variant ✔\}}}\$ ${\color{YellowOrange}{\textsf{Exact ✖ \}}}\$

>${\{\textsf{Appearance:\}}}\$
${\color{lime}{\textsf{Variant ✔\}}}\$ ${\color{YellowOrange}{\textsf{Exact ✖ \}}}\$
${\color{red}{\textsf{Class Invalid\}}}\$

---

**Some extra chars for designating the extra line(s) as "addon text", but integrated on the same line**:
<sup>1 - 2 lines
>${\{\textsf{TC:\}}}\$ ${\color{lime}{\textsf{Variant ✔\}}}\$ ${\color{YellowOrange}{\textsf{Exact ✖ \}}}\$

>${\{\textsf{TC:\}}}\$ ${\color{lime}{\textsf{Variant ✔\}}}\$ ${\color{YellowOrange}{\textsf{Exact ✖ \}}}\$
${\color{red}{\textsf{Class Invalid\}}}\$

>[!note]
>Since unlocking an appearance from it's **Exact** source satisfies the conditions for **both** of the lines in the current format, you can just display ${\color{lime}{\textsf{Exact ✔\}}}\$ and that's it!

>${\{\textsf{TC:\}}}\$ ${\color{lime}{\textsf{Exact ✔\}}}\$
${\color{red}{\textsf{Class Invalid\}}}\$

---

**Single line *every time* when literally asking "What do you have unlocked for this appearance?"**:
>${\{\textsf{TC:\}}}\$ ${\color{lime}{\textsf{Exact\}}}\$

>${\{\textsf{TC:\}}}\$ ${\color{lime}{\textsf{Exact\}}}\$ ${\color{red}{\textsf{Class Invalid\}}}\$

>${\{\textsf{TC:\}}}\$ ${\color{yellow}{\textsf{Variant\}}}\$

>${\{\textsf{TC:\}}}\$ ${\color{yellow}{\textsf{Variant\}}}\$ ${\color{red}{\textsf{Class Invalid\}}}\$

>${\{\textsf{TC:\}}}\$ ${\color{orange}{\textsf{None\}}}\$

>${\{\textsf{TC:\}}}\$ ${\color{orange}{\textsf{None\}}}\$ ${\color{red}{\textsf{Class Invalid\}}}\$

<br>

As you can see, you could quite easily display even ***more*** information with much less space. I think either of my last 2 format suggestions would make this addon feel quite polished and elegant. I would appreciate it more than I can possibly describe to you! 😔 🙏

**Comment by DelaneDiamon** [comment]
Hey, yeah, styling is not great and definitely can be improved. 
The limitation WoW has, unfortunately, is default fonts. Its default font (Arial) has support of 127 ASCII characters, so I will probably use "X" and "V" as cross and checkmark.

**Comment by Mysame** [comment]
If anything I'd say now it's a bit unclear. The `TC` , while good indication of the addon, also makes the little info shown quite confusing.
Just my 2 cents.

**Comment by Fernajj** [comment]
Is there a way to change back to the old tooltip style if I really dislike the new one?

**Comment by DelaneDiamon** [comment]
Hey @Fernajj 
I have not implemented any GUI to have some settings for styling. Is there a middle ground that would you prefer that would look more compact, but also have sufficient wording?

**Comment by Fernajj** [comment]
My issue with the new one is mainly that at a quick glance it blends in with all the stats. My typical use case is I have all my bags full of random items from transmog runs and I am trying to discern what to equip or not at a quick glance on the tooltip. Seems like the thing that the other poster wanted changed is what I liked about it. No worries if you end up keeping it how it is - just providing feedback.

**Comment by DelaneDiamon** [comment]
@Fernajj 
I understand, and my initial goal was to provide a clear way to tell if the item is collected. A lot of addons are modifying the tooltip, so there could be a lot of stats displayed. I will try to optimize it in a way that it is compact, but also visible.

**Comment by DelaneDiamon** [comment]
@Fernajj 
I gave it another iteration and I will update the addon to display the conditions below.

If the model is _**collected**_ from this exact item:
![image](https://github.com/user-attachments/assets/84a924b5-e3af-4d68-8c44-8712dc32bd24)
Not sure if the info that "it was this exact item" is useful, but it is available anyway from API for free.

If the model is _**collected from different item**_ and current class is eligible for this item to collect the model from this armor/weapon:
![image](https://github.com/user-attachments/assets/2fa6821a-4728-4600-970d-d08f13c5fd43)

If the model is _**not collected**_ and available to collect by this class:
![image](https://github.com/user-attachments/assets/ad7de9a8-574f-4b94-8e8f-85e0fb2d8257)

If the model is _**not collected**_ and class is ineligible:
![image](https://github.com/user-attachments/assets/400c3ac6-3606-4e06-8a35-bbac8ee6e571)

**Comment by Mysame** [comment]
Looks great.

**Comment by Fernajj** [comment]
It does look a lot better for my needs as well. Thank you!
