### ISSUE TITLE
"Class invalid" not always showing

### ISSUE THREAD

**Issue by Iowerth** [DelaneDiamon/Transmog-Checker#9]
Hi. Addon v0.0.9. I'm playing mage.

Mail armor item, which source and model are not collected, has "Class invalid". It is fine. https://www.wowhead.com/cata/item=55279/manacles-of-pain
But mace item, which source and model are collected, hasn't "Class invalid". Why so? Mages can't use maces. https://www.wowhead.com/cata/item=55777/torturers-mercy

**Comment by DelaneDiamon** [comment]
Hello, there is a discussion in another issue thread where there was a suggestion to make the format more compact. 

I have given it a bit of thought and made [it the following](https://github.com/DelaneDiamon/Transmog-Checker/issues/8#issuecomment-2290498585) (see message in the thread).

In short - if the model is collected - there is no reason to worry about it as you already got it. If it is not collected and the class is ineligible - it will display in red.

Let me know if this has become more confusing than before, I will try to think of other options

**Comment by Iowerth** [comment]
Thanks. But now error appear - https://github.com/DelaneDiamon/Transmog-Checker/issues/11
